export const GET_REPOSITORIES = 'GET_REPOSITORIES';
export const GET_REPOSITORIES_FAILED = 'GET_REPOSITORIES_FAILED';
export const CLEAR_REPOSITORIES = 'CLEAR_REPOSITORIES';
export const FETCH_START = 'FETCH_START';
